# Generated by Django 6.0.6 on 2026-07-01 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(help_text='Código de barras único', max_length=100, unique=True)),
                ('descripcion', models.CharField(help_text='Nombre o descripción del producto', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SesionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Inventario General Julio 2026', max_length=150)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta / En Conteo'), ('CERRADA', 'Cerrada / Finalizada')], default='ABIERTA', max_length=10)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras_detectado', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_manual', models.CharField(blank=True, default='No especificado', max_length=255, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(choices=[('NO_EXISTE', 'Artículo NO registrado / No existe'), ('ILEGIBLE', 'Código ilegible'), ('DUPLICADO', 'Artículo duplicado'), ('SIN_ETIQUETA', 'Producto sin etiqueta')], default='NO_EXISTE', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='inventario.sesioninventario')),
            ],
        ),
        migrations.CreateModel(
            name='ConteoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='inventario.sesioninventario')),
            ],
            options={
                'indexes': [models.Index(fields=['sesion', 'producto'], name='inventario__sesion__954040_idx')],
            },
        ),
    ]
