# Generated by Django 5.2.14 on 2026-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_conteodetalle_id_alter_novedad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_teorico',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad esperada en sistema según última carga'),
        ),
    ]
