# Generated by Django 5.2.14 on 2026-07-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_stock_teorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_teorico',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad esperada en sistema'),
        ),
    ]
