# Generated by Django 5.2.14 on 2026-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_conteodetalle_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='espacio',
            field=models.CharField(blank=True, help_text='Ej: A1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nivel',
            field=models.CharField(blank=True, help_text='Ej: 01, 02', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='rack',
            field=models.CharField(blank=True, help_text='Ej: Rack 01', max_length=20, null=True),
        ),
    ]
