# Generated by Django 5.2.14 on 2026-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_conteodetalle_id_alter_novedad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(help_text='Código de barras de la ubicación', max_length=100, unique=True)),
                ('rack', models.CharField(max_length=50)),
                ('espacio', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
