# Generated by Django 5.2.14 on 2026-07-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='rack',
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación física del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.ubicacion'),
        ),
    ]
