# Generated by Django 5.2.14 on 2026-08-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_producto_espacio_remove_producto_nivel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Base de Inventario', max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=10)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bases_inventario_cerradas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_inventario_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock_teorico', models.PositiveIntegerField(default=0)),
                ('rack', models.CharField(blank=True, default='', max_length=50)),
                ('espacio', models.CharField(blank=True, default='', max_length=100)),
                ('nivel', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad_contada', models.PositiveIntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.baseinventario')),
            ],
        ),
    ]
