# Generated by Django 5.2.14 on 2026-08-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_baseinventario_historialproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioninventario',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='inventario.baseinventario'),
        ),
    ]
