# Generated by Django 5.2.14 on 2026-08-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_sesioninventario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historialproducto',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.baseinventario'),
        ),
        migrations.AddIndex(
            model_name='historialproducto',
            index=models.Index(fields=['base', 'codigo_barras'], name='inventario__base_id_e33242_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproducto',
            index=models.Index(fields=['base', 'descripcion'], name='inventario__base_id_d4a3e5_idx'),
        ),
    ]
