# Generated by Django 5.2.14 on 2026-09-08 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_historialproducto_fecha_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conteodetalle',
            constraint=models.UniqueConstraint(fields=('sesion', 'producto'), name='unique_conteo_sesion_producto'),
        ),
    ]
