# Generated by Django 5.2.14 on 2026-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_conteodetalle_unique_conteo_sesion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioninventario',
            name='ajuste_aplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesioninventario',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
