# Generated by Django 5.2.14 on 2026-09-09 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_sesioninventario_ajuste_aplicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinventario',
            name='conciliacion_aplicada',
            field=models.BooleanField(default=False, help_text='Indica si la conciliación final de esta base ya fue aplicada al Maestro de Productos.'),
        ),
        migrations.AddField(
            model_name='baseinventario',
            name='conciliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bases_inventario_conciliadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseinventario',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
