# Generated by Django 5.2.14 on 2026-09-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_baseinventario_conciliacion_aplicada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesioninventario',
            name='ajuste_aplicado',
        ),
        migrations.RemoveField(
            model_name='sesioninventario',
            name='fecha_aplicacion',
        ),
    ]
