# Generated by Django 5.2.14 on 2026-09-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_sesioninventario_ajuste_aplicado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock_teorico', models.PositiveIntegerField(default=0)),
                ('rack', models.CharField(blank=True, default='', max_length=50)),
                ('espacio', models.CharField(blank=True, default='', max_length=100)),
                ('nivel', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_base', to='inventario.baseinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_historicas', to='inventario.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['base', 'codigo_barras'], name='inventario__base_id_248b23_idx'), models.Index(fields=['base', 'descripcion'], name='inventario__base_id_cc76c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'producto'), name='unique_producto_base')],
            },
        ),
    ]
