# Generated by Django 5.2.14 on 2026-09-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_transferenciainventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_por_ubicacion', to='inventario.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['producto', 'ubicacion'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'ubicacion'), name='unique_stock_producto_ubicacion')],
            },
        ),
    ]
