# Generated by Django 5.2.14 on 2026-09-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_stockubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_productos_base', to='inventario.baseinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_bases_historicas', to='inventario.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_bases_historicas', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['producto', 'ubicacion'],
                'indexes': [models.Index(fields=['base', 'producto'], name='inventario__base_id_5cdbf5_idx'), models.Index(fields=['base', 'ubicacion'], name='inventario__base_id_8b78c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'producto', 'ubicacion'), name='unique_base_producto_ubicacion')],
            },
        ),
    ]
