# Generated by Django 5.2.14 on 2026-09-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_baseproductoubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProductoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ubicaciones', to='inventario.baseinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ubicaciones', to='inventario.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_productos_ubicaciones', to='inventario.ubicacion')),
            ],
            options={
                'ordering': ['producto', 'ubicacion'],
                'indexes': [models.Index(fields=['base', 'producto'], name='inventario__base_id_745bf7_idx'), models.Index(fields=['base', 'ubicacion'], name='inventario__base_id_5559b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'producto', 'ubicacion'), name='unique_historial_producto_ubicacion')],
            },
        ),
    ]
