# Generated by Django 5.2.14 on 2026-09-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex_destino', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex_origen', to='inventario.ubicacion'),
        ),
    ]
