# Generated by Django 5.2.14 on 2026-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_registroauditoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
